# Generated by Django 4.1.3 on 2022-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricemonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default.jpg', null=True, upload_to='static/img/profile_images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('regular', 'Użytkownik'), ('moderator', 'Moderator')], default='regular', max_length=30),
        ),
    ]
