# Generated by Django 4.1.3 on 2022-12-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricemonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nazwa techniczna'),
        ),
        migrations.AlterField(
            model_name='product',
            name='verbose_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nazwa produktu'),
        ),
    ]
