# Generated by Django 4.1 on 2022-09-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricemonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(default='no address', max_length=255),
        ),
    ]
