# Generated by Django 4.1.3 on 2022-11-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricemonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('regular', 'Użytkownik'), ('moderator', 'Moderator')], default='regular', max_length=30),
        ),
    ]
