# Generated by Django 4.1.3 on 2022-11-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricemonitor', '0002_alter_userprofile_user'),
        ('pricemonitor', '0002_userprofile_role'),
    ]

    operations = [
    ]
