# Generated by Django 4.1.3 on 2022-11-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricemonitor', '0003_merge_20221112_0903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductUserRequest',
        ),
    ]
