# Generated by Django 4.1.3 on 2022-11-19 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricemonitor', '0004_delete_productuserrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricemonitor.serviceproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='pricemonitor.userprofile')),
            ],
        ),
    ]
