# Generated by Django 4.1 on 2022-09-30 13:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pricemonitor', '0004_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_url',
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='product_url',
            field=models.URLField(default='no address', max_length=255),
        ),
        migrations.CreateModel(
            name='ServiceProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('service_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricemonitor.serviceproduct')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
