# Generated by Django 4.1.3 on 2022-11-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricemonitor', '0005_userproductassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Nazwa techniczna'),
        ),
        migrations.AlterField(
            model_name='product',
            name='verbose_name',
            field=models.CharField(max_length=255, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='service',
            name='host',
            field=models.URLField(max_length=255, verbose_name='Adres URL'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=30, verbose_name='Nazwa techniczna'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('regular', 'Użytkownik'), ('moderator', 'Moderator')], default='moderator', max_length=30),
        ),
    ]
