# Generated by Django 4.1.2 on 2022-10-29 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricemonitor', '0005_rename_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=30, verbose_name='Nazwa techniczna serwisu'),
        ),
        migrations.AlterField(
            model_name='service',
            name='verbose_name',
            field=models.CharField(max_length=30, verbose_name='Nazwa serwisu'),
        ),
        migrations.CreateModel(
            name='ServiceProductDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('end_datetime', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('e', 'Błąd'), ('p', 'Oczekuje'), ('d', 'Wykonano'), ('r', 'W trakcie')], default='p', max_length=12)),
                ('error_message', models.TextField(default='')),
                ('service_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='pricemonitor.serviceproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_name', models.CharField(max_length=255, verbose_name='Nazwa produktu')),
                ('product_url', models.URLField(max_length=255, verbose_name='Link do produktu')),
                ('status', models.CharField(choices=[('p', 'Oczekuje'), ('r', 'Odrzucone'), ('a', 'Zaakceptowane')], default='p', max_length=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricemonitor.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
