# Generated by Django 4.1.3 on 2022-12-15 09:50

from django.db import migrations, models
import pricemonitor.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('pricemonitor', '0007_alter_userserviceproduct_service_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_URL',
            field=models.CharField(default='brak adresu', max_length=255, validators=[pricemonitor.models.product.validate_url], verbose_name='Link do produktu'),
        ),
    ]
